### ISSUE TITLE
INFOGRAFIA_ERS

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/infografia-Rigoberto2001-1#1]
![INF_ERS_RIGOBERTORAMIREZNICOLAS](https://user-images.githubusercontent.com/79929662/153774434-af1c6fd8-aee5-4104-927b-6661ca6d2350.png)

**Comment by christopheremv** [comment]
calificación: 18/20

**Comment by josealfredo79** [comment]
Falta lo del estandar...

**Comment by josealfredo79** [comment]
Validado
